kind: pipeline
name: default

steps:
  - name: test
    image: golang
    commands:
      - go test
      - cd app/smpp-dumb-server && go build
      - cd ../smpp-dumb-client && go build
      - cd ../smpp-lb && go build
