port: 2500

# Loglevel: trace / debug / info / warning / error / fatal / panic
logLevel: info
#logLevel: trace

# FLAG: If NetBuf should be printed in case of connection failure
debugNetBuf: true

# Logging configuration
logging:
  # Server connection
  server:
    # Incoming Rate (yes/no)
    rate: yes

# Response behaviour
responder:
  # Generate delivery reports: yes/no
  deliveryReport: yes