port: 2500

# Loglevel: trace / debug / info / warning / error / fatal / panic
logLevel: debug
#logLevel: trace

# Logging configuration
logging:
  # Server connection
  server:
    # Incoming Rate (yes/no)
    rate: no
