#
# SMPP Dumb Server configuration file
#

# Listening port
listen: 2500

# Logging configuration
log:
  # Log level: trace / debug / info / warning / error / fatal / panic
  level: info

  # Incoming Rate (yes/no)
  rate: yes

  # FLAG: If NetBuf should be printed in case of connection failure
  netbuf: true

# Authentication information
accounts:
  test:
    mode: trx
    systemID: test
    systemType: "test"
    password: test
  test01:
    mode: trx
    systemID: test01
    systemType: test01
    password: test01

# Response generation behaviour
responder:
  # MSGID Format: hex / uuid [default: hex]
  msgid: uuid

  # Response packet delay configurationDelay configuration
  delay:
    # SUBMIT_SM_RESP generation delay: MIN/MAX
    min: 1000
    max: 1000

# Delivery report generation behaviour
deliveryreport:
  # Generate delivery reports: yes/no
  enabled: yes

  # Generate custom TLV fields
  tlv:
    # Format: TLV_ID (HEX); TLV_TYPE ("hex"/"string"); TLV_VALUE
    - 0x0e;   hex;    "01"
    - 0x06;   hex;    "01"
    - 0x1502; string; "79039998877"

  # DELIVER_SM generation delay after message is accepted: MIN/MAX
  delay:
    min: 2000
    max: 2000

