# Loglevel: trace / debug / info / warning / error / fatal / panic
logLevel: info

# Server configuration
server:
  # Listen port
  port: 2775

# Logging configuration
logging:
  # Server connection
  server:
    # Incoming Rate (yes/no)
    rate: yes

# Client configuration
client:
  # Remote SMSC
  remote: 127.0.0.1:2500

