#
# SMPP Load Balancer configuration file
#

# Logging configuration
log:
  # Log level: trace / debug / info / warning / error / fatal / panic
  level: info

  # Incoming Rate (yes/no)
  rate: yes

  # FLAG: If NetBuf should be printed in case of connection failure
  netbuf: true


# Profiler configuration [ yes / no ]
profiler: yes

# Profiler listening IP:port [ default is: 127.0.0.1:5801 ]
profilerListen: 127.0.0.1:5801

# Server configuration
server:
  # Listen port
  port: 2775
  accounts:
    SysID:
      mode: trx
      systemID: SysID
      systemType: ""
      password: test
      profile: profile1
    test:
      mode: trx
      systemID: test
      systemType: test
      password: test
      profile: test


# Client configuration
client:
  # Remote SMSC
  remote: 127.0.0.1:2500
  bind:
    systemID: test
    systemType: test
    password: test


# Client connection configuration
clients:
  # Profile1: bind inherit mode
  "profile1":
    remote: 127.0.0.1:2500
    bind:
      mode: inherit
  # Test: specific bind configuration
  "test":
    remote: 127.0.0.1:2500
    bind:
      mode: trx
      systemid: "test"
      systemtype: "test"
      password: "test"
