#
# SMPP Dumb Client configuration file
#

# Logging configuration
log:
  # Log level: trace / debug / info / warning / error / fatal / panic
  level: info

  # Incoming Rate (yes/no)
  rate: yes

  # FLAG: If NetBuf should be printed in case of connection failure
  netbuf: true


# Profiler configuration [ yes / no ]
profiler: yes

# Profiler listening IP:port [ default is: 127.0.0.1:5800 ]
profilerListen: 127.0.0.1:5800

# Remote IP:port
remote: 127.0.0.1:2500

# Bind parameters
bind:
  systemID: test
  systemType: test
  password: test
  # Connection mode: TRX/TX/RX (default: TRX)
  mode: TRX

# Message submission parameters
message:
  from:
    ton: 5
    npi: 0
    addr: ThisIsMe
  to:
    ton: 1
    npi: 1
    addr: 79032496449
  registeredDelivery: 1
  dataCoding: 1
  body: "This is message for sending"
  tlv:
# List of TLV fields, structure: CODE; TYPE; VALUE
    - 0x1880; string; "App.Name.Rec"
    - 0x1890; string; "Record Data"
    - 0x1900; hex; "0102030405"

# Number of messages to send
count: 100000000
#count: 1

# Submission rate
rate: 5

# Submission TX window
window: 100

# Should we stay connected after sending messages [ default: no ]
stayConnected: yes
