# Loglevel: trace / debug / info / warning / error / fatal / panic
logLevel: debug
#logLevel: trace

# Profiler configuration [ yes / no ]
profiler: yes

# Profiler listening IP:port [ default is: 127.0.0.1:5800 ]
profilerListen: 127.0.0.1:5800

# Remote IP:port
remote: 192.168.4.98:2500

# Bind parameters
bind:
  systemID: test
  systemType: test
  password: test

# Message submission parameters
message:
  from:
    ton: 5
    npi: 0
    addr: ThisIsMe
  to:
    ton: 1
    npi: 1
    addr: 79032496449
  registeredDelivery: 1
  dataCoding: 1
  body: "This is message for sending"

# Number of messages to send
count: 1000

# Submission rate
rate: 10

# Submission TX window
window: 100

