name: Build_Linux_x86-64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        cd app/smpp-dumb-client
        go get -v -t -d ./...
        cd ../smpp-dumb-server
        go get -v -t -d ./...
        cd ../smpp-lb
        go get -v -t -d ./...
        cd ../..
                
    - name: Build
      run: | 
        go test
        cd app/smpp-dumb-client
        go build -v .
        cd ../smpp-dumb-server
        go build -v .
        cd ../smpp-lb
        go build -v .
        cd ../..
    - name: Test
      run: |
        cd app/smpp-dumb-server
        go test -v .
        cd ../smpp-dumb-client
        go test -v .
        cd ../smpp-lb
        go test -v .
        cd ../..
    - name: Prepare artefacts
      run: |
        mkdir -p out/smpp-dumb-client out/smpp-dumb-server out/smpp-lb
        cp app/smpp-dumb-server/smpp-dumb-server out/smpp-dumb-server/
        cp app/smpp-dumb-server/config.yml out/smpp-dumb-server/
        cp app/smpp-dumb-client/smpp-dumb-client out/smpp-dumb-client/
        cp app/smpp-dumb-client/config.yml out/smpp-dumb-client/
        cp app/smpp-lb/smpp-lb out/smpp-lb/
        cp app/smpp-lb/config.yml out/smpp-lb/
        find out/
    - name: Upload linux binary
      uses: actions/upload-artifact@master
      with:
        name: linux_x86-64
        path: out        
              
